server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  type-aliases-package: com.cduestc.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xm

spring:
  application:
  name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  security:
    user:
      name: test
      password: 123456
eureka:
  client: #将客户端注册进eureka服务列表
    service-url:
      defaultZone: http://test:123456@eureka7001.com:7001/eureka/,http://test:123456@eureka7002.com:7002/eureka/,http://test:123456@eureka7003.com:7003/eureka/

  instance:
    appname: microservicecloud-dept8001
    prefer-ip-address: true #鼠标放在注册信息上，右下角显示ip
    instance-id: microservicecloud-dept8001

#信息描述
info:
  app.name: cduestc-microservicecloud
  company.name: www.cduestc.cn
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}





