server:
  port: 80
eureka:
  client: #将客户端注册进eureka服务列表
    register-with-eureka: false
    service-url:
      defaultZone: http://test:123456@eureka7001.com:7001/eureka/,http://test:123456@eureka7002.com:7002/eureka/,http://test:123456@eureka7003.com:7003/eureka/